name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./assignment/node-fibonacci
          push: true
          tags: dipakyadav780/my-node-app:latest
          
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure_resource_group: assignment
          kubernetes_cluster: test-fibonaci
          command: |
            kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml 
            kubectl set image deployment/my-node-app-deployment my-node-app-container=dipakyadav780/my-node-app:latest   
