---
name: Build & Push Docker Image
on:
  push:
    branches:
      - main
env:
  CLUSTER_RESOURCE_GROUP: assignment
  CLUSTER_NAME: test-fibonaci
  NAMESPACE: test-fibo
  CONTAINER_REGISTRY_SECRET: mysecretname
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./assignment/node-fibonacci
          push: true
          tags: dipakyadav780/my-node-app:latest
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build_and_push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: v0.0.24
      - name: Login Azure Kubernates
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: "true"
          use-kubelogin: "true"
      - name: Bake deployment
        uses: azure/k8s-bake@v2
        with:
          renderEngine: helm
          helmChart: ./K8s/helm-poc/
          helm-version: latest
        id: bake
      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          namespace: ${{ env.NAMESPACE }}
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ secrets.DOCKER_USERNAME }}/my-node-app
          imagepullsecrets: |
            ${{ env.CONTAINER_REGISTRY_SECRET }}
